//------------------------------------------------------------------------
// Copyright(c) 2025 Marco Garzetti.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"vst-organ.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"vst-organ VST3 (64Bit)"
#else
#define stringFileDescription	"vst-organ VST3"
#endif
#define stringCompanyName		"Marco Garzetti\0"
#define stringLegalCopyright	"Copyright(c) 2025 Marco Garzetti."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
